name: Suggestion
description: Here's something you can add to the website.
title: "[SUGGEST] "
labels:
  - "suggestion"
body:
  - type: markdown
    attributes:
      value: Please read the [contributing guidelines](https://github.com/discuitnet/docs/blob/main/.github/CONTRIBUTING.md) before contributing.

  - type: checkboxes
    attributes:
      label: Have you read the contributing guidelines?
      options:
        - label: I have read the contributing guidelines.
          required: true

  - type: textarea
    attributes:
      label: What is your suggestion?
      description: Give as much detail as you can.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Would you like to work on this?
      options:
        - label: I would like to work on this.
          required: false
